name: freezeds
description: Flutter入門
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  arkit_plugin:
  flutter:
    sdk: flutter
  flutter_riverpod:
  flutter_hooks:
  riverpod_annotation:

dev_dependencies:
  freezed:
  build_runner:
  json_serializable:
  flutter_test:
    sdk: flutter
  flutter_lints:
  riverpod_generator:
  envied_generator:

flutter:
  uses-material-design: true


